_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/baseline

NAME: general_model

PREPROCESS:
  OVERWRITE: False
  DISABLE_CHECK: False

  RESIZE:
    RESIZE_MODE: "scaling"
    SCALING: 0.5
    MAX_SIZE: -1

  BASELINE:
    LINE_WIDTH: 10
    SQUARE_LINES: True

INPUT:
  FORMAT: RGB

  RESIZE_MODE: "scaling"
  SCALING_TRAIN: 1.0
  MAX_SIZE_TRAIN: -1

  MAX_SIZE_TEST: -1

  CROP:
    ENABLED: True
    SIZE: [1024, 1024]
    TYPE: absolute

  GRAYSCALE:
    PROBABILITY: 1.

  ADAPTIVE_THRESHOLDING:
    PROBABILITY: 1.

  BRIGHTNESS:
    PROBABILITY: 1.
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  CONTRAST:
    PROBABILITY: 1.
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  SATURATION:
    PROBABILITY: 1.
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  HUE:
    PROBABILITY: 1.
    MIN_DELTA: -0.25
    MAX_DELTA: 0.25

  INVERT:
    PROBABILITY: 1.

  JPEG_COMPRESSION:
    PROBABILITY: 1.
    MIN_QUALITY: 50
    MAX_QUALITY: 100

  NOISE:
    PROBABILITY: 1.
    MIN_STD: 10
    MAX_STD: 32

  GAUSSIAN_FILTER:
    PROBABILITY: 1.
    MIN_SIGMA: 0.5
    MAX_SIGMA: 1.5

  HORIZONTAL_FLIP:
    PROBABILITY: 1.

  VERTICAL_FLIP:
    PROBABILITY: 1.

  ELASTIC_DEFORMATION:
    PROBABILITY: 1.
    ALPHA: 0.1
    SIGMA: 0.01

  AFFINE:
    PROBABILITY: 1.

    TRANSLATION:
      PROBABILITY: 1.
      STANDARD_DEVIATION: 0.02

    ROTATION:
      PROBABILITY: 1.
      KAPPA: 30.

    SHEAR:
      PROBABILITY: 1.
      KAPPA: 20.

    SCALE:
      PROBABILITY: 1.
      STANDARD_DEVIATION: 0.12

  ORIENTATION:
    PROBABILITY: 1.
    PERCENTAGES: (0.25, 0.25, 0.25, 0.25)

DATALOADER:
  NUM_WORKERS: 32
  FILTER_EMPTY_ANNOTATIONS: False

SOLVER:
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 25000
  BASE_LR: 0.0002
  GAMMA: 0.1
  STEPS: () #(80000, 120000, 160000)
  MAX_ITER: 250000

MODEL:
  MODE: baseline

  SEM_SEG_HEAD:
    NUM_CLASSES: 2

  AMP_TRAIN:
    ENABLED: True

  WEIGHTS:

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS:
  EVAL_PERIOD: 10000
