name: Unittests

on: [push, pull_request]

jobs:
  unittests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          miniforge-version: "latest"
          environment-file: environment.yml
      
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list

      - name: Test image utils
        if: always()
        run: |
          python tests/test_image_utils.py
      
      - name: Test input utils
        if: always()
        run: |
          python tests/test_input_utils.py
